name: Delete Successful Workflows

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:
  
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Successful Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 3
          delete_run_by_conclusion: success